### ISSUE TITLE
Client should be interface not concrete type

### ISSUE THREAD

**Issue by KevinAnthony** [fastly/go-fastly#124]
Since client is a struct, it is impossible to inject and test using the client.
as the goism says `accept interfaces, return structs`

**Comment by Integralist** [comment]
👋🏻 

The go-fastly API client is a struct with various API endpoints accessible via methods off the concrete type. 

To mock this client, a user can have their function accept an interface of the methods they want to use.

As an example, this is done in the Fastly CLI ([interface](https://github.com/fastly/cli/blob/main/pkg/api/interface.go) and a [mock interface for tests](https://github.com/fastly/cli/blob/main/pkg/mock/api.go)).

With this in mind, and considering the age of the issue, and the fact we now have [a code-generated Fastly API client](https://github.com/fastly/fastly-go) that is likely to supersede go-fastly at some point in the future,  I'm going to close this issue as it's unlikely we're going to change the design at this point.
