### ISSUE TITLE
Add HTTPS logging endpoint support

### ISSUE THREAD

**Issue by softprops** [fastly/go-fastly#185]
https://docs.fastly.com/en/guides/log-streaming-https is [available via the API](https://docs.fastly.com/api/logging#api-section-logging_https) but has no client interface I can see.

**Comment by ezkl** [comment]
HTTPS endpoint support was added with https://github.com/fastly/go-fastly/pull/155 and released in [v1.9.0](https://github.com/fastly/go-fastly/blob/master/CHANGELOG.md#190---2020-04-23).

**Comment by softprops** [comment]
whoops. my bad. thanks!
