### ISSUE TITLE
Support Fastly-managed TLS subscriptions

### ISSUE THREAD

**Issue by Sytten** [fastly/go-fastly#186]
That would be great, because it could then be exposed to the terraform provider.

**Comment by Integralist** [comment]
@Sytten thanks for opening this issue (and for your patience waiting for a reply).

We have TLS parity scheduled across Go-Fastly and our [terraform provider](https://github.com/fastly/terraform-provider-fastly).

I can't give an exact timeline, but it should hopefully be coming soon.

**Comment by dcrodman** [comment]
Hi @Integralist , I'm also looking for this feature and poking through the code it seems like this support exists now. Can you confirm and if so should this ticket be closed out? Thanks!

**Comment by Integralist** [comment]
Hi @dcrodman 👋🏻 

Yes! This is both in go-fastly and in our terraform provider. Thanks for the reminder to close off this issue 🙂 

Here are the terraform [docs](https://registry.terraform.io/providers/fastly/fastly/latest/docs).

The go-fastly [docs](https://pkg.go.dev/github.com/fastly/go-fastly/v5/fastly) can be trickier (IMO) to navigate so I'd personally recommend just reading over the code files for [TLS](https://github.com/fastly/go-fastly/blob/main/fastly/tls.go), [TLS Subscriptions](https://github.com/fastly/go-fastly/blob/main/fastly/tls_subscription.go) or [Platform TLS](https://github.com/fastly/go-fastly/blob/main/fastly/platform_tls.go) depending on which you require.
