### ISSUE TITLE
Fails to Parse Historic Stats when no Service Provided

### ISSUE THREAD

**Issue by quiffman** [fastly/go-fastly#214]
Trying to fetch historical stats without specifying a service fails with `source data must be an array or slice, got map`.

e.g.

```golang
     stats, err := client.GetStats(&fastly.GetStatsInput{
         Field:  "bandwidth",
         From:   "2020-06-01",
         To:     "2020-07-01",
         By:     "day",
         Region: "all",
     })
     if err != nil {
         log.Fatal(err)
     }
```

I've been toying around with the following modification to `stats.go`:

```diff
diff --git a/fastly/stats.go b/fastly/stats.go
index 26698ef..088147e 100644
--- a/fastly/stats.go
+++ b/fastly/stats.go
@@ -96,10 +96,10 @@ type GetStatsInput struct {
 
 // StatsResponse is a response from the service stats API endpoint
 type StatsResponse struct {
-       Status  string            `mapstructure:"status"`
-       Meta    map[string]string `mapstructure:"meta"`
-       Message string            `mapstructure:"msg"`
-       Data    []*Stats          `mapstructure:"data"`
+       Status  string              `mapstructure:"status"`
+       Meta    map[string]string   `mapstructure:"meta"`
+       Message string              `mapstructure:"msg"`
+       Data    map[string][]*Stats `mapstructure:"data"`
 }
 
 // GetStats returns stats data based on GetStatsInput
```

But I'm not going to raise that in a pull request as it fundamentally changes the response structure and obviously needs prior discussion.

**Comment by phamann** [comment]
Hey @quiffman, thank you for raising this feature request and suggesting a solution. 

I agree that this seems like a good addition, however as it would be a breaking change we wouldn't be able to change this until a v2.0.0 release for the library. Another option would be to expose a new non-breaking get all stats method `func (c *Client) GetStatsAll(i *GetStatsAllInput) (*StatsAllResponse, error)` or similar. 

Fortunately we're beginning to plan for a v2.0.0 release so I will add this to that tracking. But let me know your thoughts on the above options.
