### ISSUE TITLE
Potentially misleading comment in README.md

### ISSUE THREAD

**Issue by marklkelly** [fastly/go-fastly#260]
In the README

```
// Get the latest active version
latest, err := client.LatestVersion(&fastly.LatestVersionInput{
  ServiceID: serviceID,
})
if err != nil {
  log.Fatal(err)
}
```
The comment states `Get the latest active version`

Not sure if the expectation is that it would fetch the latest active version, but `client.LatestVersion` will fetch the latest version, regardless of its state (active or draft).

We should consider providing a helper to get the latest active version - or an update to README to demonstrate the correct way to fetch the active version.

**Comment by dkegel-fastly** [comment]
This isn't quite fixed, the type of latest is wrong... I'd create a pull request if I had permissions to.

**Comment by Integralist** [comment]
Thanks @dkegel-fastly I've got a PR open to correct the README example now https://github.com/fastly/go-fastly/pull/275
