### ISSUE TITLE
Support S3 logging `acl`, new `redundancy` options

### ISSUE THREAD

**Issue by tpansino** [fastly/go-fastly#278]
The SDK for working with S3 logging appears to be missing support for some properties of the [API](https://developer.fastly.com/reference/api/logging/s3/). Specifically:

- `acl` is not currently a supported value
- `redundancy` is missing support for Infrequent Access and One Zone Infrequent Access

[This](https://github.com/fastly/go-fastly/blob/main/fastly/s3.go) looks like the main file that needs to be updated, but also I am not a Go developer. 😅

**Comment by Integralist** [comment]
Hi @tpansino thank you for raising this issue.

API parity with our go-fastly client is something we're actively working on, and so we'll take this and figure out where it sits in the priority order. Unfortunately I can't give an ETA on this, but I'll provide feedback once we're ready to implement.

**Comment by Integralist** [comment]
Hi @tpansino I've released `3.7.0` which has the missing ACL/Redundancy options added:

https://github.com/fastly/go-fastly/releases/tag/v3.7.0
