### ISSUE TITLE
GetService returns a Service with null version

### ISSUE THREAD

**Issue by stefangluszek** [fastly/go-fastly#311]
[Client.GetService](https://pkg.go.dev/github.com/fastly/go-fastly/v5/fastly#Client.GetService) returns [Service](https://pkg.go.dev/github.com/fastly/go-fastly/v5/fastly#Service) and according to the documentation it should have [ActiveVersion](https://github.com/fastly/go-fastly/blob/v5.1.0/fastly/service.go#L19) but that is always null. This is because the underlying API for service does not return the version. There is a similar method [GetServiceDetails](https://pkg.go.dev/github.com/fastly/go-fastly/v5/fastly#Client.GetServiceDetails) that returns [ServiceDetail](https://pkg.go.dev/github.com/fastly/go-fastly/v5/fastly#ServiceDetail) which will have both ActiveVersion and Version fields. This is confusing as the readers of the documentation would expect Service returned by GetService to have a proper Version set.

**Comment by karenetheridge** [comment]
as per https://developer.fastly.com/reference/api/services/service/#search-service, active version is not included in this endpoint. The associated versions are provided in array though, and exactly one of those versions will have `"active":true`.

**Comment by Integralist** [comment]
I'm going to close this PR as it looks to be something that will be clarified via the public documentation.
