### ISSUE TITLE
UpdateBackend() can't clear OverrideHost and other fields?

### ISSUE THREAD

**Issue by dkegel-fastly** [fastly/go-fastly#371]
The omitempty in UpdateBackendInput appears to prevent callers from clearing OverrideHost and other fields.

**Comment by bdournaee** [comment]
This is affecting a customer using the signal sciences edge deployment. Any help appreciated in addressing it.

**Comment by dkegel-fastly** [comment]
Looks like I was confused, and the real problem I was trying to solve lies elsewhere.
