### ISSUE TITLE
TLSActivation Struct does not support mutual_authentication key which the API returns

### ISSUE THREAD

**Issue by landrew57** [fastly/go-fastly#532]
The TLSActivation struct defined does not support the `mutual_authentication` field that is returned by the API. This means any requests to 'get' an activation after updating it cannot confirm the activation is exactly as intended.

https://github.com/fastly/go-fastly/blob/557b0b967d5ab6574b6d089fa1f3ef70b56c7658/fastly/tls_custom_activation.go#L13-L19

Adding support for `mutual_authentictation` would mean that the terraform provider could determine if changes have been made to the `mutual_configuration` field. Currently it cannot because that field is not unmarshaled during the [resourceFastlyTLSActivationRead function](https://github.com/fastly/terraform-provider-fastly/blob/e4c1f63c029e47b291bb4e029ee4338e3448350c/fastly/resource_fastly_tls_activation.go#L77-L107).

Example API call returning `mutual_authentication` and the other keys that are Marshaled into the Struct:

```bash
$ curl -s  "https://api.fastly.com/tls/activations/<example_activation>" -H "Fastly-Key: $(fastly profile token -o user -q)" -H "Accept: application/vnd.api+json" | jq
{
  "data": {
    "id": "<example_activation>",
    "type": "tls_activation",
    "attributes": {
      "created_at": "2024-06-11T14:46:17.000Z"
    },
    "relationships": {
      "tls_certificate": {
        "data": {
          "id": "<example_cert>",
          "type": "tls_certificate"
        }
      },
      "tls_configuration": {
        "data": {
          "id": "<example_configuration>",
          "type": "tls_configuration"
        }
      },
      "tls_domain": {
        "data": {
          "id": "<example_domain>",
          "type": "tls_domain"
        }
      },
      "mutual_authentication": {
        "data": null
      }
    }
  }
}
```

**Comment by Integralist** [comment]
@landrew57 Thanks for opening this issue. I've created an internal ticket to track this and we'll update this issue once we have more information.

**Comment by kpfleming** [comment]
Even more bizarre, this field is present in the `UpdateTLSActivationInput` struct, so this code was touched after `mutual_authentication` was added to the API.

**Comment by Integralist** [comment]
https://github.com/fastly/go-fastly/pull/535
