### ISSUE TITLE
 support in_use filtering in CustomTLSCertificate and PrivateKey

### ISSUE THREAD

**Issue by relvira** [fastly/go-fastly#533]
Hey there,

It looks like go-fastly doesn't support the `in_use` filter that your API does support for [Custom TLS Certificates](https://www.fastly.com/documentation/reference/api/tls/custom-certs/certificates/) and [Private Keys](https://www.fastly.com/documentation/reference/api/tls/custom-certs/private-keys/).

I was figuring if this is something you folks can build into the golang library, as it is greatly useful for automating some processes around TLS certificates in Fastly.

Thank you!
Rafa.

**Comment by Integralist** [comment]
👋🏻 @relvira 

Thanks for raising this issue, yes we can add that field.

The `in_use` query was added to the Fastly API last year, while the rest of the TLS feature set was added to go-fastly long before that. So this new API addition slipped through the net as far as the go-fastly API client is concerned.

cc @kpfleming

**Comment by relvira** [comment]
Thank you for the quick response here @Integralist 🙇🏼 I definitely appreciate your interest in implementing this feature into go-fastly. 

Would you have an estimate (days, weeks, months) in mind to have the feature implemented into the library? This will help us manage expectations on our side. 🙌🏼

**Comment by kpfleming** [comment]
Unfortunately we do not yet have an estimate; if we did, we'd probably be restricted from communicating it in a public place anyway :-) Please open a support ticket in Zendesk referring to this GitHub issue so that we can track the 'Fastly customer' aspects of the issue there. Thanks!

**Comment by Integralist** [comment]
FYI it looks like it's already implemented in...

- https://pkg.go.dev/github.com/fastly/go-fastly/v9@v9.6.0/fastly#ListTLSDomainsInput
- https://pkg.go.dev/github.com/fastly/go-fastly/v9@v9.6.0/fastly#ListPrivateKeysInput

It's only missing from https://pkg.go.dev/github.com/fastly/go-fastly/v9@v9.6.0/fastly#ListCustomTLSCertificatesInput

**Comment by Integralist** [comment]
👋🏻 

The following PR only took a couple of minutes for me to put together: https://github.com/fastly/go-fastly/pull/534

**Comment by relvira** [comment]
Thank you for putting up that PR @Integralist 🙇🏼  - do you have a set cadence for creating releases in go-fastly? or is that ad-hoc?

**Comment by Integralist** [comment]
No problem @relvira 

Yeah, the release cycle currently is very much ad-hoc, but will eventually move to a more consistent/structured release cycle soon.

@kpfleming would you be OK publishing a new release? Looking at the commit history there is only this recent change and one other change that would be included in the next release (I'm not aware of any other work upcoming that we'd want to wait for).

**Comment by kpfleming** [comment]
I'll give it a try!
